In [1]:
"""
【示例1】创建3×4的Ndarray对象。
"""
# 引入Numpy模块
import numpy as np
# 平安银行股价
payh = [15.16,15.13,15.24,15]
# 兰州银行股价
lzyh = [3.63,3.65,3.66,3.63]
# 宁波银行股价
nbyh = [33.31,33.21,33.41,33.02]
# 构建 一个3×4的ndarray对象stock_array
stock_array = np.array([payh,lzyh,nbyh], dtype=float)
# 打印ndarray对象stock_array
print(stock_array)


[[15.16 15.13 15.24 15.  ]
 [ 3.63  3.65  3.66  3.63]
 [33.31 33.21 33.41 33.02]]


In [4]:
"""
【示例2】创建2×3的空Ndarray对象。
"""
# 创建一个维度为2×3，数据类型为整数型int的ndarray对象
stock_empty = np.empty((2,3),dtype=int)
# 打印stock_empty的数据
print(stock_empty)
# 打印stock_empty的数据类型
print(type(stock_empty))


[[    3276849     3014711  1285111296]
 [        563           0 -2147483648]]
<class 'numpy.ndarray'>


In [5]:
"""
【示例3】创建2×3的0值Ndarray对象
"""
# 生成一个维度为2×3、数据类型为默认float64类型的ndarray对象
zero_int_ndarray = np.zeros(shape=(2,3))
# 打印zero_int_ndarray
print(zero_int_ndarray)
# 生成一个维度为2×3、数据类型为字符串str类型的ndarray对象
zero_str_ndarray = np.zeros(shape=(2,3),dtype=str)
# 打印zero_str_ndarray
print(zero_str_ndarray)


[[0. 0. 0.]
 [0. 0. 0.]]
[['' '' '']
 ['' '' '']]


In [7]:
"""
【示例4】索引方式访问Ndarray对象数据单元素。
"""
# 创建1维数组a，元素值分别为“1、2、3、4、5”
array_one_level = np.array([1, 2, 3, 4, 5])
# 打印1维数组a中第3个元素，索引号为2
print(array_one_level[2])  


3


In [8]:
"""
【示例5】索引方式访问Ndarray对象数据多元素。
"""
# 创建1维数组a，元素值分别为“1、2、3、4、5”
array_one_level = np.array([1, 2, 3, 4, 5])
# 输出1维数值中第1、3、5个元素，即[1, 3, 5]
print(array_one_level[[0, 2, 4]])  


[1 3 5]


In [9]:
"""
【示例6】索引访问多维数组内单一元素。
"""
# 输出第2行第3列的元素
array_mul_level = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_mul_level[1, 2])  


6


In [10]:
"""
【示例7】索引访问多维数组内多元素。
"""
# 输出第1行第2列和第3行第1列的元素
array_mul_level = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_mul_level[[0, 2], [1, 0]])  


[2 7]


In [11]:
"""
【示例8】获取数组指定行数据。
"""
array = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
# 打印ndarray对象array
print('原数组：\n',array)
print('----------')
# 打印ndarray对象第2行（索引号为1）
print('原数组第2行数据：\n',array[1])


原数组：
 [[1 2 3]
 [3 4 5]
 [4 5 6]]
----------
原数组第2行数据：
 [3 4 5]


In [16]:
"""
【示例9】获取指定列数据。
"""
array = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
# 打印第2列（索引号为1）
print('原数组第2列数据：\n',array[:, 1])


原数组第2列数据：
 [2 4 5]


In [17]:
"""
【示例10】获取指定行以后所有数据。
"""
array = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
# 打印第2行及之后的所有行的数据
print('第2行及之后的所有行的数据：\n',array[1:, ])


第2行及之后的所有行的数据：
 [[3 4 5]
 [4 5 6]]


In [19]:
"""
【示例11】获取数组中大于2的元素。
"""
array = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
# 打印ndarray对象数组x中大于2的元素。
print(array[array>2])


[3 3 4 5 4 5 6]


In [20]:
"""
【示例12】通过多维数组进行花式切片。
"""
# 构造一个2维3×8个元素的ndarray对象数组
x=np.arange(24).reshape((3, 8))

# 打印ndarray对象数组
print('原数组：\n',x)

# 打印ndarray对象数组的第2、1行数据
print('\n 数组的第2、1行数据：\n',x[[2, 1]])

# 打印ndarray对象数组的第3、1、7列数据
print('\n 数组的第3、1、7列数据：\n',x[:, [3, 1, 7]])


原数组：
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

 数组的第2、1行数据：
 [[16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]]

 数组的第3、1、7列数据：
 [[ 3  1  7]
 [11  9 15]
 [19 17 23]]


In [21]:
"""
【示例13】reshape方法应用。
"""
# 创建一维ndarray对象，元素分别为[0 1 2 3 4 5 6 7]
array_oldshape = np.arange(8)
print('原始数组：\n', array_oldshape)

# 修改ndarray对象为2×4数组，order为默认值“C”（行优先）
array_newshape_C = np.reshape(array_oldshape,[2,4])
print('\n 修改后的数组，order排序默认为“C”：\n', array_newshape_C)

# 修改ndarray对象2×4数组，order设为“F”（列优先）
array_newshape_F = np.reshape(array_oldshape,[2,4],order='F')
print('\n 修改后的数组，order排序为“F”：\n', array_newshape_F)


原始数组：
 [0 1 2 3 4 5 6 7]

 修改后的数组，order排序默认为“C”：
 [[0 1 2 3]
 [4 5 6 7]]

 修改后的数组，order排序为“F”：
 [[0 2 4 6]
 [1 3 5 7]]


In [22]:
"""
【示例14】flatten方法应用。
"""
a = np.array([[1,2,3,4],[5,6,7,8]])
print('原数组：\n', a)
print('\n以默认“C”风格顺序order展开的数组：\n', a.flatten())
print('\n以 “F”风格顺序order展开的数组：\n', a.flatten(order='F'))


原数组：
 [[1 2 3 4]
 [5 6 7 8]]

以默认“C”风格顺序order展开的数组：
 [1 2 3 4 5 6 7 8]

以 “F”风格顺序order展开的数组：
 [1 5 2 6 3 7 4 8]


In [23]:
"""
【示例15】transpose方法。
"""
# 创建一个2×3×4维度的ndarray对象
array = np.arange(24).reshape(2,3,4)
print('原数组数据为：\n', array)
print('\n 修改为2×4×3维度数据：\n', array.transpose((0,2,1)) )


原数组数据为：
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 修改为2×4×3维度数据：
 [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [24]:
"""
【示例16】合并数组。
"""
array1 = np.array([[1,2], [3,4]]) 
print('第1个数组原始数据：\n', array1)

array2 = np.array([[5,6], [7,8]])
print('\n 第2个数组原始数据：\n')

# 两个数组的维度需要相同
print ('\n 沿轴 0 连接两个数组：\n' ,np.concatenate((array1, array2)))
print ('\n 沿轴 1 连接两个数组：\n', np.concatenate((array1, array2), axis=1))


第1个数组原始数据：
 [[1 2]
 [3 4]]

 第2个数组原始数据：


 沿轴 0 连接两个数组：
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 沿轴 1 连接两个数组：
 [[1 2 5 6]
 [3 4 7 8]]


In [25]:
"""
【示例17】拆分数组。

"""
#创建一个维度为4×4的ndarray对象
array = np.arange(16).reshape(4,4)
print('打印ndarray对象原数据 \n', array)
print('\n 默认按行索引号为1、2进行分割数组数据：\n')
print(np.split(a, [1, 2]))

print('\n axis=1，按列索引号为1、2进行分割数组数据：')
print(np.split(a, [1, 2], axis=1))


打印ndarray对象原数据 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 默认按行索引号为1、2进行分割数组数据：

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]

 axis=1，按列索引号为1、2进行分割数组数据：
[array([[1],
       [5]]), array([[2],
       [6]]), array([[3, 4],
       [7, 8]])]


In [26]:
"""
【示例18】删除数组单一数据。
"""
# 要删除ndarray对象arr中索引为1的元素
arr = np.array([1, 2, 3, 4, 5])
print('原数组：\n',arr)
new_arr = np.delete(arr, 1)
print('\n删除后的数组：\n',new_arr)


原数组：
 [1 2 3 4 5]

删除后的数组：
 [1 3 4 5]


In [27]:
"""
【示例19】删除指定行、列数据。
"""
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('原数据：\n',arr)
# 删除第1行
new_arr = np.delete(arr, 0, axis=0)  
print('\n删除1行后的数据：\n',new_arr)


原数据：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

删除1行后的数据：
 [[4 5 6]
 [7 8 9]]


In [28]:
"""
【示例20】切片删除数据。
"""
# 删除第1列与第3列数据
new_arr = np.delete(arr, [0, 2], axis=1) 
print(new_arr)


[[2]
 [5]
 [8]]


In [29]:
"""
【示例21】数组添加数据。
"""
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])
print(new_arr)


[1 2 3 4 5 6]


In [30]:
"""
【示例22】数组添加行数据。
"""
# 添加一行数据。
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = np.append(arr, [[7, 8, 9]], axis=0)  
print(new_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
"""
【示例23】数组添加列数据。
"""
# 添加一列数据。
new_arr = np.append(arr, [[10], [11]], axis=1)  
print(new_arr)


[[ 1  2  3 10]
 [ 4  5  6 11]]


In [32]:
"""
【示例】统计类函数
"""
import numpy as np

# 假设这是某只股票过去 5 天的收盘价
prices = np.array([100, 102, 101, 105, 107])

# 计算平均价格
mean_price = np.mean(prices)
print(f"平均收盘价: {mean_price}")

# 计算收盘价的中位数
median_price = np.median(prices)
print(f"收盘价中位数: {median_price}")

# 计算收盘价的标准差
std_price = np.std(prices)
print(f"收盘价标准差: {std_price}")

# 计算收盘价的方差
var_price = np.var(prices)
print(f"收盘价方差: {var_price}")

# 计算最低价和最高价
min_price = np.min(prices)
max_price = np.max(prices)
print(f"最低价: {min_price}, 最高价: {max_price}")

# 假设这是某只股票过去 5 天的成交量
volumes = np.array([1000, 1200, 1100, 1300, 1400])

# 计算总成交量
total_volume = np.sum(volumes)
print(f"总成交量: {total_volume}")

# 计算收盘价的 25% 和 75% 分位数
percentile_25 = np.percentile(prices, 25)
percentile_75 = np.percentile(prices, 75)
print(f"25% 分位数: {percentile_25}, 75% 分位数: {percentile_75}")

# 计算收盘价的直方图
hist, bin_edges = np.histogram(prices, bins=3)
print(f"直方图统计: {hist}")
print(f"区间边界: {bin_edges}")

# 假设这是另一只股票过去 5 天的收盘价
prices_2 = np.array([90, 92, 91, 95, 97])

# 计算两只股票价格的相关系数矩阵
corr_matrix = np.corrcoef(prices, prices_2)
print("相关系数矩阵:")
print(corr_matrix)

# 计算两只股票价格的协方差矩阵
cov_matrix = np.cov(prices, prices_2)
print("协方差矩阵:")
print(cov_matrix)

平均收盘价: 103.0
收盘价中位数: 102.0
收盘价标准差: 2.6076809620810595
收盘价方差: 6.8
最低价: 100, 最高价: 107
总成交量: 6000
25% 分位数: 101.0, 75% 分位数: 105.0
直方图统计: [3 0 2]
区间边界: [100.         102.33333333 104.66666667 107.        ]
相关系数矩阵:
[[1. 1.]
 [1. 1.]]
协方差矩阵:
[[8.5 8.5]
 [8.5 8.5]]


In [35]:
"""
【示例】线性代数类函数
"""
import numpy as np

# 假设有3只股票的日收益率
returns = np.array([0.02, 0.01, -0.005])  # 3只股票的日收益率

# 假设我们投资这3只股票的权重分别是 0.5, 0.3, 0.2
weights = np.array([0.5, 0.3, 0.2])

# 计算投资组合的日收益率（加权和）
portfolio_return = np.dot(returns, weights)
print(f'投资组合的日收益率: {portfolio_return:.2%}')


# 假设有3只股票的每日收益率数据，每一列表示一只股票的收益
data = np.array([[0.02, 0.01, -0.005],
                 [0.03, 0.02, -0.002],
                 [-0.01, 0.005, 0.003]])

# 计算数据的转置
data_transposed = np.transpose(data)

print("转置后的收益数据：")
print(data_transposed)


# 假设我们有一个协方差矩阵
cov_matrix = np.array([[0.04, 0.01, 0.005],
                       [0.01, 0.03, 0.002],
                       [0.005, 0.002, 0.02]])

# 计算协方差矩阵的迹（即对角线元素的和）
trace_value = np.trace(cov_matrix)
print(f'协方差矩阵的迹: {trace_value}')


# 假设我们有一个协方差矩阵
cov_matrix = np.array([[0.04, 0.01],
                       [0.01, 0.03]])

# 计算协方差矩阵的行列式
det_value = np.linalg.det(cov_matrix)
print(f'协方差矩阵的行列式: {det_value}')


# 假设我们有一个2x2的协方差矩阵
cov_matrix = np.array([[0.04, 0.01],
                       [0.01, 0.03]])

# 计算协方差矩阵的逆
cov_matrix_inv = np.linalg.inv(cov_matrix)
print("协方差矩阵的逆：")
print(cov_matrix_inv)

# 假设我们有一个2x2的收益率数据矩阵
data = np.array([[0.02, 0.01],
                 [0.03, 0.02]])

# 计算奇异值分解
U, S, Vt = np.linalg.svd(data)

print("左奇异矩阵 U：")
print(U)
print("奇异值 S：")
print(S)
print("右奇异矩阵 Vt：")
print(Vt)

# 假设有一个表示股票回报的向量
returns = np.array([0.02, 0.03, -0.01])

# 计算该回报向量的欧几里得范数（即L2范数）
norm_value = np.linalg.norm(returns)
print(f'回报向量的L2范数: {norm_value}')

投资组合的日收益率: 1.20%
转置后的收益数据：
[[ 0.02   0.03  -0.01 ]
 [ 0.01   0.02   0.005]
 [-0.005 -0.002  0.003]]
协方差矩阵的迹: 0.09000000000000001
协方差矩阵的行列式: 0.0011
协方差矩阵的逆：
[[27.27272727 -9.09090909]
 [-9.09090909 36.36363636]]
左奇异矩阵 U：
[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]
奇异值 S：
[0.04236068 0.00236068]
右奇异矩阵 Vt：
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
回报向量的L2范数: 0.03741657386773942


In [30]:
"""
【示例24】计算数组直方图数据。
"""
np.histogram(np.arange(4), bins=np.arange(5), density=True)

(array([0.25, 0.25, 0.25, 0.25]), array([0, 1, 2, 3, 4]))

In [32]:
"""
【示例25】Numpy求解方程组。
"""
# 将原方程组视为AX=B，通过构建ndarray数组A与B，求解未知数X向量。
A = np.array([[3, 3, 2],
             [2, 5, 2],
             [1, 2, 4]])
B = np.array([18, 17, 10])
X = np.linalg.solve(A, B)
print("自变量向量解：",X)


自变量向量解： [4.   1.5  0.75]


In [33]:
"""
【示例26】一维数组排序。
"""
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
# 沿着最后一个轴排序（默认值）
sorted_arr = np.sort(arr)
print("沿着最后一个轴排序（默认值）：\n",sorted_arr,"\n") 


沿着最后一个轴排序（默认值）：
 [1 1 2 3 3 4 5 5 6 9] 



In [36]:
"""
【示例27】按指定轴排序。
"""
# 沿着第1个轴排序
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5], [3, 5, 8]])
sorted_arr = np.sort(arr, axis=0)
print("沿着第1个轴排序：\n",sorted_arr,"\n")


沿着第1个轴排序：
 [[1 1 4]
 [2 5 5]
 [3 5 8]
 [3 6 9]] 



In [37]:
"""
【示例28】带有字段的数组排序。
"""
# 排序带有字段的数组
dtype = [('name', 'S10'), ('age', int)]
values = [('Alice', 25), ('Bob', 18), ('Charlie', 32), ('David', 23)]
arr = np.array(values, dtype=dtype)
sorted_arr = np.sort(arr, order='name')
print("排序带有字段的数组：\n",sorted_arr)


排序带有字段的数组：
 [(b'Alice', 25) (b'Bob', 18) (b'Charlie', 32) (b'David', 23)]


In [38]:
"""
【示例29】argsort函数返回排序后的索引号。
"""
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
# 沿着最后一个轴排序（默认值）
sorted_arr = np.argsort(arr)
print("沿着最后一个轴排序（默认值）：\n",sorted_arr,"\n") 


沿着最后一个轴排序（默认值）：
 [1 3 6 0 9 2 4 8 7 5] 



In [39]:
"""
【示例30】使用argsort函数按指定列排序。
"""
# 按4×3数组的第2列值进行排列
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5], [3, 5, 8]])
print('原数据：\n', arr)
# 获取第2列值排序后的索引号
sorted_indices = np.argsort(arr[:, 1])
# 原数组按新的索引号排序
sorted_arr = arr[sorted_indices]
print('\n按第2列数据排序：\n',sorted_arr) 


原数据：
 [[3 1 4]
 [1 5 9]
 [2 6 5]
 [3 5 8]]

按第2列数据排序：
 [[3 1 4]
 [1 5 9]
 [3 5 8]
 [2 6 5]]


In [38]:
"""
【示例31】创建3×4的Ndarray对象。

"""
a = np.array([[2, 7, 8, 4], [5, 1, 3, 6]])
print('原始ndarray对象数据为：')
print(a)
print('------------------------------------------------')
print('按行进行argmax排序：')
print(np.argmax(a, axis=0))
print('------------------------------------------------')
print('按列进行argmin排序：')
print(np.argmin(a, axis=1))


原始ndarray对象数据为：
[[2 7 8 4]
 [5 1 3 6]]
------------------------------------------------
按行进行argmax排序：
[1 0 0 1]
------------------------------------------------
按列进行argmin排序：
[0 1]


In [39]:
"""
【示例32】where应用。
"""
arr1 = np.array([8, -2, 9, 4])
print('原数组1：',arr1)
arr2 = np.array([5, 6, 7, 8])
print('原数组2：',arr2)
new_arr = np.where(arr1 > 0, arr1, 0)
print('将小于0的元素转变为0：',new_arr)

# 不指定x和y参数，只返回符合条件的索引
idx = np.where(arr1 > 2)
print('仅设置条件时，返回符合条件的索引，而非具体元素值：',idx)  # (array([2, 3]),)

# 指定x和y参数，返回对应值
new_arr = np.where(arr1>arr2, arr1, arr2)
print('数组1＞数组2时，选数组1值，否则选数组2值：',new_arr)


原数组1： [ 8 -2  9  4]
原数组2： [5 6 7 8]
将小于0的元素转变为0： [8 0 9 4]
仅设置条件时，返回符合条件的索引，而非具体元素值： (array([0, 2, 3], dtype=int64),)
数组1＞数组2时，选数组1值，否则选数组2值： [8 6 9 8]


In [40]:
"""
【示例33】创建2×3的随机均匀分布的数组。
"""
# 生成一个二维2×3的随机数据矩阵数组，全部值服从“0~1”均匀分布的随机样本值。随机样本取值范围是[0,1)，即包括0但不包括1。
array_normal = np.random.rand(2,3)
array_normal

array([[0.28362075, 0.67385199, 0.01873946],
       [0.36577538, 0.96886344, 0.9612499 ]])

In [41]:
"""
【示例34】创建随机整数数组。
"""
print("生成1维5个不高于2的整数数组：",np.random.randint(2, size=5))
print("生成0-5之间的整数型2×3数组：\n",np.random.randint(0,5,size=(2,3)))

生成1维5个不高于2的整数数组： [1 0 1 1 1]
生成0-5之间的整数型2×3数组：
 [[4 4 0]
 [1 1 4]]


In [42]:
"""
【示例35】choice函数随机抽查。
"""
a = np.array([1, 2, 3, 4, 5])
# 从a数组中随机抽查3个元素，不允许重复抽样，且原数组a中各元素被抽查的概率按参数p的设定概率进行抽取。
b = np.random.choice(a, size=3, replace=False, p=[0.8, 0.1, 0.05, 0.025, 0.025])
print(b)


[1 3 2]


In [42]:
"""
【示例36】掷骰子模拟实验。
"""
# 模拟掷骰子实验，100 次试验，每个面出现的概率相等，均为1/6。
dice_roll = np.random.choice(a=[1, 2, 3, 4, 5, 6], size = 100, replace = True, p = [1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

# 输出实验结果
print("掷骰子实验结果：", dice_roll)
print("每个面出现的次数：", np.bincount(dice_roll, minlength=6))


掷骰子实验结果： [4 3 3 6 5 5 1 6 5 5 2 5 3 4 6 3 6 6 3 3 3 6 1 6 4 5 5 3 1 6 3 3 5 2 4 5 6
 5 1 4 2 3 1 3 3 5 3 2 4 6 3 3 4 1 4 1 4 6 5 1 5 5 6 2 5 2 3 1 3 1 2 2 4 4
 5 1 1 2 1 2 3 1 3 4 2 6 1 6 1 3 1 1 4 1 1 2 2 4 6 1]
每个面出现的次数： [ 0 21 13 21 14 16 15]


In [46]:
"""
【示例37】蒙特卡罗模拟实验。
"""
# 设置股票价格的基本参数和模型
S0 = 100    # 初始股票价格
mu = 0.1    # 年化收益率
sigma = 0.2    # 年化波动率
T = 1    # 投资期限（年）
N = 252    # 投资期限内的交易日数
dt = T / N    # 时间步长

# 生成蒙特卡罗模拟实验的随机路径
M = 10000    # 模拟实验的路径数
S = np.zeros((M, N+1))    # 存储所有路径的股票价格
S[:, 0] = S0
for i in range(1, N+1):
    # 根据几何布朗运动模型生成每个时间步的股票价格
    S[:, i] = S[:, i-1] * np.exp((mu - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*np.random.normal(size=M))

# 计算每条路径的收益率
r = np.diff(S, axis=1) / S[:, :-1]

# 计算未来股票价格的期望值、方差、置信区间等统计特征
mean = np.mean(S[:, -1])
std = np.std(S[:, -1])
conf_int = np.percentile(S[:, -1], [2.5, 97.5])

# 输出结果
print("期望股票价格：", mean)
print("标准差：", std)
print("95%置信区间：", conf_int)


期望股票价格： 110.5531252369683
标准差： 22.494500757870348
95%置信区间： [ 73.19593441 160.74921202]
